export const AT_DOMAINS = [
  "archive.today", "archive.ph", "archive.is",
  "archive.fo", "archive.li", "archive.vn", "archive.md",
];

export const TOPICS = [
  { id: "medicine", label: "Medicine", icon: "\u{1FA7A}", cats: ["Category:Medicine", "Category:Diseases and disorders", "Category:Medical treatments", "Category:Drugs", "Category:Epidemiology", "Category:Pathology", "Category:Medical specialties", "Category:Public health", "Category:Radiology", "Category:Surgery", "Category:Pharmacology", "Category:Vaccines"] },
  { id: "biology", label: "Biology", icon: "\u{1F9EC}", cats: ["Category:Biology", "Category:Genetics", "Category:Molecular biology", "Category:Microbiology", "Category:Ecology", "Category:Botany", "Category:Zoology"] },
  { id: "physics", label: "Physics", icon: "\u269B\uFE0F", cats: ["Category:Physics", "Category:Quantum mechanics", "Category:Astrophysics", "Category:Particle physics", "Category:Nuclear physics"] },
  { id: "chemistry", label: "Chemistry", icon: "\u{1F9EA}", cats: ["Category:Chemistry", "Category:Chemical elements", "Category:Organic chemistry", "Category:Biochemistry", "Category:Chemical compounds"] },
  { id: "cs", label: "Computer Science", icon: "\u{1F4BB}", cats: ["Category:Computer science", "Category:Artificial intelligence", "Category:Machine learning", "Category:Programming languages", "Category:Cryptography", "Category:Software", "Category:Algorithms"] },
  { id: "history", label: "History", icon: "\u{1F4DC}", cats: ["Category:History", "Category:Ancient history", "Category:Medieval history", "Category:Modern history", "Category:World War II", "Category:World War I", "Category:History of science", "Category:Historiography"] },
  { id: "politics", label: "Politics", icon: "\u{1F3DB}\uFE0F", cats: ["Category:Politics", "Category:Elections", "Category:Political parties", "Category:Heads of state", "Category:International relations", "Category:Diplomacy"] },
  { id: "geography", label: "Geography", icon: "\u{1F30D}", cats: ["Category:Geography", "Category:Countries", "Category:Cities", "Category:Islands", "Category:Rivers", "Category:Mountains"] },
  { id: "law", label: "Law", icon: "\u2696\uFE0F", cats: ["Category:Law", "Category:Criminal law", "Category:International law", "Category:Human rights", "Category:Supreme Court of the United States"] },
  { id: "economics", label: "Economics", icon: "\u{1F4CA}", cats: ["Category:Economics", "Category:Macroeconomics", "Category:Microeconomics", "Category:Finance", "Category:Monetary policy", "Category:International trade"] },
  { id: "engineering", label: "Engineering", icon: "\u{1F527}", cats: ["Category:Engineering", "Category:Electrical engineering", "Category:Civil engineering", "Category:Mechanical engineering", "Category:Aerospace engineering"] },
  { id: "media", label: "Media & Journalism", icon: "\u{1F4F0}", cats: ["Category:Mass media", "Category:Journalism", "Category:Newspapers", "Category:Television", "Category:Radio", "Category:Podcasts"] },
  { id: "environment", label: "Environment", icon: "\u{1F331}", cats: ["Category:Environmentalism", "Category:Climate change", "Category:Pollution", "Category:Conservation", "Category:Renewable energy", "Category:Sustainability"] },
  { id: "education", label: "Education", icon: "\u{1F393}", cats: ["Category:Education", "Category:Universities and colleges", "Category:Schools", "Category:Educational technology", "Category:Academic disciplines"] },
  { id: "sports", label: "Sports", icon: "\u26BD", cats: ["Category:Sports", "Category:Olympic Games", "Category:Football", "Category:Cricket", "Category:Basketball", "Category:Tennis"] },
];

export const C = {
  bg: "#FAF9F5",
  bgAlt: "#F0EEE6",
  card: "#FFFFFF",
  cardBorder: "#E8E6DE",
  text: "#141413",
  textSec: "#3D3D3A",
  muted: "#73726C",
  mutedLight: "#A3A29C",
  accent: "#D97757",
  accentHover: "#C4684B",
  accentSoft: "rgba(217,119,87,0.08)",
  accentBorder: "rgba(217,119,87,0.2)",
  green: "#2E7D5B",
  greenSoft: "rgba(46,125,91,0.08)",
  greenBorder: "rgba(46,125,91,0.2)",
  red: "#C4533A",
  redSoft: "rgba(196,83,58,0.08)",
  redBorder: "rgba(196,83,58,0.2)",
  amber: "#A67A2E",
  amberSoft: "rgba(166,122,46,0.08)",
  amberBorder: "rgba(166,122,46,0.2)",
  blue: "#3B6BA5",
  blueSoft: "rgba(59,107,165,0.06)",
  blueBorder: "rgba(59,107,165,0.18)",
  btnDark: "#3D3D3A",
  btnDarkHover: "#2A2A28",
  mono: "'IBM Plex Mono',monospace",
  serif: "'Source Serif 4',Georgia,serif",
  sans: "'Inter',-apple-system,sans-serif",
  radius: "12px",
  radiusSm: "8px",
  shadow: "0 1px 3px rgba(0,0,0,0.04),0 1px 2px rgba(0,0,0,0.02)",
  shadowMd: "0 4px 12px rgba(0,0,0,0.06),0 1px 3px rgba(0,0,0,0.04)",
};
